### ISSUE TITLE
apply pull request 

### ISSUE THREAD

**Issue by netpyoung** [netpyoung/unity.libsodium#3]
https://github.com/netpyoung/unity.libsodium/pull/2

# TODO
* prepare editorconfig, gitattribute

* advance : how to autogen.cs for new added function?

**Comment by Ekwav** [comment]
About the `autogen.cs`, maybe scrap the current docs from https://download.libsodium.org/doc/* 
then select all functions with this regex: `\Rint (.|\R)*?\);\R`, 
select the parameters types and replace them with the equivalent in c#,
write the result into the `NativeLibsodium` class.
Not sure how future proof this would be.

**Comment by netpyoung** [comment]
yes. I also not sure which way is good or not. so I just postpone.

they also hardcoding that
https://github.com/adamcaudill/libsodium-net/blob/master/libsodium-net/Interop/SodiumLibrary.cs

**Comment by Ekwav** [comment]
Indeed, they are also missing the latest APIs for Sodium 1.0.16 
But I think there will be less and less new functions because as the [roadmap](https://download.libsodium.org/doc/roadmap) says
> New features will be gladly implemented provided that they are not redundant and solve common problems.

New functions are most likely redundant of existing ones.
So maybe it is even overkill to take the time and make a `autogen.cs`

**Comment by netpyoung** [comment]
yes. It is better to add manually now.
and I already applied your pull request. 
Okay I will close this issue.
